"""Alembic migration environment for AeroCast-NCR.

The database URL is resolved, in order, from:
  1. `-x db_url=...` on the command line (recommended for CI), read via
     `context.get_x_argument(as_dictionary=True)` -- NOT `get_main_option`,
     which cannot see `-x` and silently fell through to DATABASE_URL,
  2. a `db_url` option in alembic.ini,
  3. the DATABASE_URL environment variable,
  4. the app's settings (backend.app.config) as a final fallback.

Options 1 and 2 are *explicit*: if the value they supply is blank or not a valid
SQLAlchemy URL, resolution raises (`DbUrlResolutionError`) instead of quietly
migrating a different database. The chosen target is logged with any password
masked, so a mistarget is visible before any DDL runs.

Autogenerated revisions target the SQLAlchemy metadata in backend.app.models.
"""

import os
import sys
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Ensure the backend package is importable so the metadata below resolves.
# The backend root must come BEFORE any other entry that exposes a package
# named ``app``: the repository root holds a tiny ``app/`` shim for Render's
# stock ``uvicorn app.main:app`` command, and that shim has no ``database``
# submodule. A plain "if not in sys.path" guard was not enough - when
# PYTHONPATH already listed the backend root, the guard skipped the insert and
# the shim won, so ``alembic upgrade head`` failed with
# "No module named 'app.database'" only when PYTHONPATH was set.
_backend_root = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "backend")
while _backend_root in sys.path:
    sys.path.remove(_backend_root)
sys.path.insert(0, _backend_root)

if config.attributes.get("configure_logger", True):
    pass

import app.models.db_models  # noqa: E402,F401  register tables on Base.metadata
from app.database import Base  # noqa: E402
from scripts.alembic_db_url import resolve_db_url  # noqa: E402

target_metadata = Base.metadata


def _resolve_db_url() -> str:
    """Resolve the migration target, honouring `-x db_url=...` above all else.

    See `scripts.alembic_db_url` for why `get_x_argument` (not
    `get_main_option`) is the right accessor and why an explicit-but-broken
    override raises rather than silently falling back to DATABASE_URL.
    """
    from app.config import get_settings

    return resolve_db_url(
        x_arguments=context.get_x_argument(as_dictionary=True),
        main_option=config.get_main_option("db_url"),
        environ=os.environ,
        settings_loader=lambda: get_settings().database_url,
    )


def run_migrations_offline() -> None:
    context.configure(
        url=_resolve_db_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        url=_resolve_db_url(),
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
